name: Build README and deploy Datasette

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need full history to introspect created/updated:
      with:
	fetch-depth: 0
	path: main
    - name: Checkout scratch-db
      uses: actions/checkout@v2
      with:
	repository: stefanzweig/scratch-db
	path: scratch-db
	token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
	python-version: 3.12
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
	path: ~/.cache/pip
	key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
	restore-keys: |
	  ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
	path: ~/.cache/ms-playwright/
	key: ${{ runner.os }}-browsers
    - name: Install Python dependencies
      run: |
	python -m pip install --upgrade pip
	pip install -r main/requirements.txt
    - name: Install Playwright dependencies
      run: |
	shot-scraper install
    - name: Download previous database unless REBUILD in commit message
      if: |-
	!contains(github.event.head_commit.message, 'REBUILD')
      run: curl --fail -o main/scratch.db  https://github.com/stefanzweig/scratch-db/raw/main/scratch.db
      continue-on-error: true
    - name: Build database
      run: |-
	cd main
	python build_database.py
    - name: Soundness check
      run: |-
	cd main
	datasette . --get / | grep "Stefan Scratches"
    - name: Generate missing screenshots
      env:
	AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
	AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |-
	cd main
	python generate_screenshots.py
	sqlite-utils vacuum scratch.db
    - name: Update README
      run: |-
	cd main
	python update_readme.py --rewrite
	cat README.md
    - name: Commit and push if README changed
      run: |-
	cd main
	git diff
	git config --global user.email "actions@users.noreply.github.com"
	git config --global user.name "README-bot"
	git diff --quiet || (git add README.md && git commit -m "Updated README")
	git push
    - name: Upload latest scratch.db to the S3 bucket
      env:
	AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
	AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |-
	s3-credentials put-object tils.liuhaijiang.com scratch.db main/scratch.db
    - name: Save scratch.db to stefanzweig/scratch-db
      run: |-
	cd scratch-db
	cp ../main/scratch.db .
	git add scratch.db
	git commit --amend --no-edit
	git push --force
    - name: Deploy Datasette using Vercel
      env:
	NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
	cd main
	datasette publish vercel scratch.db \
	  --token $NOW_TOKEN \
	  --project scratch \
	  --scope stefanzweigs-projects \
	  --metadata metadata.yaml \
	  --static static:static \
	  --install datasette-template-sql \
	  --install "datasette-sitemap>=1.0" \
	  --install "datasette-atom>=0.7" \
	  --install datasette-json-html \
	  --install beautifulsoup4 \
	  --install "datasette-debug-asgi>=1.1" \
	  --install "datasette-graphql>=2.2" \
	  --install datasette-block-robots \
	  --plugins-dir plugins \
	  --template-dir templates \
	  --public
